### ISSUE TITLE
Can't load ROMs

### ISSUE THREAD

**Issue by cricri-pingouin** [djpadbit/fxgnuboy#1]
I've got tetris.gb and alleyway.gb in my storage, and I don't get to select them as I would expect from main.c:

chpos = menu_filechooser("*.gb;*.gbc","Choose ROM",(char*)&romn,chpos);

**Comment by cricri-pingouin** [comment]
By the way, I'm on a Casio 9860g Slim, running firmware v2.04, and have copied the emu .g1a and the two unzipped .gb roms with Casio FA-124 to the calculator storage.

**Comment by cricri-pingouin** [comment]
J'ai re-essaye apres optimisation memoire + reset, et pareil: le programme se lance et se ferme direct , bouh :(

**Comment by djpadbit** [comment]
Is the calculator SH4 or SH3 ? You can check using something like gintctl ([here](https://github.com/djpadbit/fxgnuboy/files/5378027/gintctl.zip)'s a build). It's not compatible with SH3 calculators.

**Comment by cricri-pingouin** [comment]
Ah, ok, the 9860g slim is SH3, so that explains. Thanks. Maybe something to add to the readme?
